### ISSUE TITLE
Use logShow

### ISSUE THREAD

**Issue by xgrommx** [restaumatic/purescript-specular#11]
Hello @zyla

How can I use `logShow` for debugging?

**Comment by xgrommx** [comment]
Okay, looks like I understand how can I do it in `view` but how can I do it in `control`?

```purescript
module Main where

import Prelude

import Control.Monad.Eff.Console as Console
import Control.Monad.Aff.Class (liftAff)
import Control.Monad.Aff.Console (logShow)
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Class (liftEff)
import Control.Monad.IO (launchIO, runIO)
import Control.Monad.IO.Effect (INFINITY)
import Control.Monad.IOSync (runIOSync)
import Control.Monad.IOSync.Class (liftIOSync)
import Data.Newtype (class Newtype, unwrap, wrap)
import Data.Tuple (Tuple(..))
import Specular.Dom.Builder.Class (dynText, el, text)
import Specular.Dom.Node.Class ((:=))
import Specular.Dom.Widget (class MonadWidget, runMainWidgetInBody)
import Specular.Dom.Widgets.Button (buttonOnClick)
import Specular.Dom.Widgets.Input (textInputOnInput)
import Specular.FRP (class MonadHold, Dynamic, Event, dynamic_, fixFRP, foldDyn, leftmost, subscribeDyn, subscribeDyn_)
import Specular.FRP.Async (startIO)
import Specular.FRP.WeakDynamic (WeakDynamic)
import Unsafe.Coerce (unsafeCoerce)

type EventModel = { increment :: Event Unit, decrement :: Event Unit, reset :: Event Unit, message :: Dynamic String }

mainWidget :: forall m. MonadWidget m => m Unit
mainWidget = fixFRP $ view >=> control

view :: forall m. MonadWidget m => { value :: WeakDynamic Int } -> m EventModel
view {value} = do
  el "p" $ dynText (show <$> value)

  increment <- buttonOnClick (pure $ "class" := "increment") $ text "Increment"
  decrement <- buttonOnClick (pure $ "class" := "decrement") $ text "Decrement"
  reset <- buttonOnClick (pure $ "class" := "reset") $ text "Reset"
  message <- textInputOnInput "message" ("class" := "text")

  -- subscribeDyn_ (\x -> launchIO $ liftAff $ logShow x) message
  subscribeDyn_ (\x -> launchIO $ liftEff $ Console.logShow x) message  

  pure { increment, decrement, reset, message }

control :: forall m. MonadHold m => EventModel -> m (Tuple { value :: Dynamic Int } Unit)
control {increment, decrement, reset, message} = do
  value <- foldDyn ($) 0 $
    leftmost
      [ (_ + 1) <$ increment
      , (_ - 1) <$ decrement
      , const 0 <$ reset
      ]
  pure (Tuple {value} unit)

main :: Eff (infinity :: INFINITY) Unit
main = runIOSync $ runMainWidgetInBody mainWidget
```

**Comment by xgrommx** [comment]
Another question, how can I use `purescript-affjax`?

**Comment by zyla** [comment]
Hello!

Your debugging line in `view` can be simplified to:

```purescript
subscribeDyn_ (liftEff <<< Console.logShow) message
```

No need to use `IO` (which is a wrapper around `Aff`) here - `IOSync` directly supports `Eff`.

> how can I do it in control

Just the same - you just need to change the constraint from `MonadHold` to `MonadFRP`. I need to change it in the example - `MonadHold` really shouldn't be exposed.

I have added a section about this to the (just created) tutorial: [Observing values and events](https://github.com/restaumatic/purescript-specular/blob/tutorial-1/doc/Tutorial.md#observing-values-and-events). Is it clear for you? You can further comment on it here: [Pull Request #12 - Tutorial](https://github.com/restaumatic/purescript-specular/pull/12).

> how can I use purescript-affjax

You can use affjax in `IO` via `liftAff`. Take a look at the `performEvent` and `asyncRequest` functions. There will be a section about this in the tutorial, once it's finished.

Thanks for checking out the library. Hope it's useful for you. If you have any further questions, please ask.

**Comment by xgrommx** [comment]
@zyla Thanks! I used reflex-frp and used idea with `subscribeEvent` But the same approach doesn't work in specular.

```purescript
counter2 :: forall m. MonadWidget m => m Unit
counter2 = do
  el "div" $ do
    fixFRP_ $ \omega -> do
      {fire: fireUser, event: eventUser} :: {fire :: Int -> IOSync Unit, event :: Event Int} <- newEvent

      flip (subscribeEvent_) omega.getUser $ \_ -> do
        response <- liftAff $ get ("https://api.github.com/users/" <> "xgrommx")
        fireUser $ response.response
        pure unit

      flip (subscribeEvent_) eventUser $ \response -> do
        liftEff $ Console.logShow response
    
      getUser <- buttonOnClick (pure $ "class" := "get-user") $ text "Get User"

      pure { getUser }
  pure unit 
```

but I got error.
```
 No type class instance was found for

    Control.Monad.Aff.Class.MonadAff ( ajax :: AJAX
                                     | t2
                                     )
                                     IOSync
```
As I understand inside `subscribeEvent_` I can use `Eff/Aff` via `liftEff/liftAff` but it doesn't work.

**Comment by xgrommx** [comment]
Also for example will be better to know about some example how can I dynamically add widgets. For example todomvc
Thanks

**Comment by xgrommx** [comment]
And docs) for example how we can use all `fixWhatEver`
for example I cannot use it in another `fixFRP` because fixFRP doesn't work with `a -> IOSync Unit`

```purescript
svg :: forall m. MonadWidget m => m (Int -> IOSync Unit)
svg = do
  fixFRP $ \_ -> do
    {fire, event} <- newEvent

    flip (subscribeEvent_) event $ \v -> do
      liftEff $ Console.log $ "log => " <> show v

    el "div" $ text "test"
    pure $ Tuple {} fire
```

**Comment by xgrommx** [comment]
@zyla Are you here?)

**Comment by zyla** [comment]
I'm not sure what this svg widget is supposed to do. But it seems that it
has to react to an externally triggered action with an Int parameter - in
that case it should take an `Event Int` as parameter instead of returning
trigger function. `Event` can be used with fixFRP.

**Comment by xgrommx** [comment]
@zyla sorry, what do u mean? I updated sample with `svg` (this was old version)

**Comment by zyla** [comment]
@xgrommx Why is the example returning an `Int -> IOSync Unit` function?

Or do you just want an example that uses `fixFRP`?

**Comment by xgrommx** [comment]
@zyla for control data outside

**Comment by xgrommx** [comment]
@zyla sorry for this again, but I still cannot to use `ajax` in specular. 
Could you please create some example with `ajax`?
Thanks!

**Comment by xgrommx** [comment]
@zyla I did it! But now I have problem with `svg` it inserted in DOM, but doesn't have some width or hight (`svg` I provided above)

**Comment by zyla** [comment]
@xgrommx Since the original `logShow` question is answered, I'm closing the issue. If you have further question, ask on fpchat (`@mbieleck` in `#purescript`) or in another GitHub issue.
