### ISSUE TITLE
combineDynamic or similar

### ISSUE THREAD

**Issue by paulyoung** [restaumatic/purescript-specular#35]
I think I'm looking for something like [`combineDyn`](https://hackage.haskell.org/package/reflex-0.4.0.1/docs/Reflex-Dynamic.html#v:combineDyn) from Reflex.

Am I overlooking an existing way to do that?

**Comment by zyla** [comment]
Hi, thanks for asking.

The desired behavior can be achieved with just the `Applicative` instance for `Dynamic`:

```purescript
combineDyn f a b = pure (f <$> a <*> b)
```

 I'm not sure why `combineDyn` exists; maybe it's specialized for performance.

Does that answer your question?

**Comment by mckeankylej** [comment]
combineDyn is purely a vestige of when Dynamic wasn’t an applicative due to performance concerns.

**Comment by paulyoung** [comment]
@zyla thanks, I ended up doing what you suggested and meant to follow up saying just that.
