### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by BartAdv** [restaumatic/purescript-specular#36]
Yeah, probably not a good use of issue tracker but bear with me:)

1. How it differs in terms of performance characteristics from reflex? I'm specifically talking about the event network and propagation, as I understand from point of view of DOM it should be similar (no vdom etc). I don't know the details, but I recall one of the main selling points of reflex was what's internally called "spider" - how does specular compares here? Any benchmarks that don't include DOM?

2. What the status is - is it just experimental software, or had it found its use somewhere?

3. How are you talking issues with memory management? Reflex uses weak references and finalizers, typescript sodium API puts additional burden on user to avoid leaks, what about specular?

Anyway - thanks for the attempt on bringing real-deal FRP to the purescript world, I hope you'll succeed!

**Comment by zyla** [comment]
Very good questions!

> 1. How it differs in terms of performance characteristics from reflex?

The event propagation machinery in Specular is pretty naive, and is slow as a
result. I am not smart (or persistent) enough to understand how Spider works,
so I don't exactly know how the two libraries differ in this respect.

> Any benchmarks that don't include DOM?

See <https://github.com/restaumatic/purescript-specular/blob/master/bench/Bench/Primitives.purs>.

> 2. What the status is - is it just experimental software, or had it found its use somewhere?

I do use it in production. So far I've hit maybe two "mysterious" bugs related
to the FRP machinery. I wish I had more time to improve performance though - on
mobile devices it's a real problem.

> 3. How are you talking issues with memory management?

Specular uses a scoped memory management scheme. In `MonadWidget` you can
register _cleanup actions_, which get run when that widget is destroyed (in
case of DOM widgets - removed from the DOM). Functions which consume FRP
primitives (`subscribeEvent_`, `subscribeDyn_`, but also DOM-building functions
like `dynText`) do this internally.

> Anyway - thanks for the attempt on bringing real-deal FRP to the purescript world, I hope you'll succeed!

Thank you for the encouragement.

**Comment by zyla** [comment]
@BartAdv I hope the above comment answers your questions. If not, please reopen :)
