### ISSUE TITLE
Best way to work around the lack of RecursiveDo?

### ISSUE THREAD

**Issue by malte-v** [restaumatic/purescript-specular#59]
Sorry if this is a dumb question, I'm a total beginner in FP :)

In the README you mentioned that it may be a little cumbersome creating recursive data flows in Specular due to the lack of MonadFix and RecursiveDo. Could you give an example how to implement a button with a number on it that increases each time the button is pressed? That would be pretty simple in Reflex but I have no idea how to implement it in PureScript. Thanks!

**Comment by soupi** [comment]
I think you can use `fixFRP` to emulate recursive do.

This is not exactly what you asked, but I have some (maybe a bit old) code that uses fixFRP to create two textboxes which depend on one another.

- [Code](https://gitlab.com/gilmi/morse/-/blob/master/src/Main.purs) - note the definition of `widget` on line 25
- [In Action](https://gilmi.gitlab.io/morse/)

**Comment by malte-v** [comment]
Thanks, that's exactly what I was looking for! Just to answer my own question:

```purs
main :: Effect Unit
main =
  runMainWidgetInBody
    $ fixFRP_ \evIncr -> do
        dynCount <- foldDyn (+) (0 :: Int) (evIncr $> 1)
        evIncr <- buttonOnClick (pure mempty) (dynText $ weaken $ show <$> dynCount)
        pure evIncr
```
