### ISSUE TITLE
Possible inaccuracy in the Motivation document

### ISSUE THREAD

**Issue by kRITZCREEK** [restaumatic/purescript-specular#8]
Hey, amazing library! Super stoked to try this out.

In https://github.com/restaumatic/purescript-specular/blob/master/doc/Motivation.md#halogen-1 you say

> As far as I know, there's no such thing as "initial effect" - you have to send the pages some kind of Init message on route change to let them fetch their data.

Halogen components have a lifecycle concept, which allows you to add hooks that will be dispatched as queries, eg:

https://github.com/slamdata/purescript-halogen/blob/ab5077243e3130d040513e4c0292d1cc5f6575ef/examples/lifecycle/src/Child.purs#L33

Would that solve the issue you're describing?

**Comment by zyla** [comment]
Hi, thanks for pointing it out. Yes, that would solve the issue.

I am slowly realizing that such a document requires far more work than I first thought - there are more inaccuracies there, and I won't have time to fix them in the near future. So this document should probably disappear until I (or someone else) find time to write it properly.

**Comment by kRITZCREEK** [comment]
Please don't! It was a really good read, cite from Slack:

> loganmac [7:00 PM] 
wow yeah https://github.com/restaumatic/purescript-specular/ is pretty awesome. If nothing else, for the very succinct descriptions and list of drawbacks of other approaches in the Motivation doc.

Don't worry about the tiny problem in there. It's still so much better than most comparisons out there that just call Halogen "safe", Thermite "not production ready" and Pux "the elm architecture"
